ALTER TABLE `aox`.`sys_banner` MODIFY COLUMN `id` bigint NOT NULL auto_increment COMMENT '主键ID';
ALTER TABLE `aox`.`sys_banner` MODIFY COLUMN `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID';
ALTER TABLE `aox`.`sys_banner` MODIFY COLUMN `title` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Banner标题';
ALTER TABLE `aox`.`sys_banner` MODIFY COLUMN `image_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '图片URL';
ALTER TABLE `aox`.`sys_banner` MODIFY COLUMN `link_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '跳转链接';
ALTER TABLE `aox`.`sys_banner` MODIFY COLUMN `link_type` int NULL DEFAULT '0' COMMENT '链接类型：0-无，1-内部页面，2-外部链接';
ALTER TABLE `aox`.`sys_banner` MODIFY COLUMN `sort_order` int NULL DEFAULT '0' COMMENT '排序（数字越小越靠前）';
ALTER TABLE `aox`.`sys_banner` MODIFY COLUMN `status` int NULL DEFAULT '1' COMMENT '状态：0-下架，1-上架';
ALTER TABLE `aox`.`sys_banner` MODIFY COLUMN `deleted` tinyint NULL DEFAULT '0' COMMENT '删除标记 0正常 1删除';
ALTER TABLE `aox`.`sys_notice` MODIFY COLUMN `notice_level` tinyint NULL DEFAULT '1' COMMENT '公告级别 1普通 2重要 3紧急';
ALTER TABLE `aox`.`sys_notice` MODIFY COLUMN `publish_user_id` bigint NULL DEFAULT NULL COMMENT '发布人ID';
ALTER TABLE `aox`.`sys_notice` MODIFY COLUMN `publish_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '发布人姓名';
ALTER TABLE `aox`.`sys_notice` MODIFY COLUMN `target_type` tinyint NULL DEFAULT '0' COMMENT '目标类型 0全部 1指定用户 2指定角色 3指定部门';
ALTER TABLE `aox`.`sys_notice` MODIFY COLUMN `is_top` tinyint NULL DEFAULT '0' COMMENT '是否置顶 0否 1是';
ALTER TABLE `aox`.`sys_notice` MODIFY COLUMN `top_order` int NULL DEFAULT '0' COMMENT '置顶排序';
ALTER TABLE `aox`.`sys_notice` MODIFY COLUMN `attachment_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '附件URL';
ALTER TABLE `aox`.`sys_notice` MODIFY COLUMN `read_count` int NULL DEFAULT '0' COMMENT '阅读次数';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `id` bigint NOT NULL auto_increment COMMENT '主键ID';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `tenant_id` bigint NULL DEFAULT '0' COMMENT '租户ID';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `storage_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '存储类型';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `is_current` tinyint NULL DEFAULT '0' COMMENT '是否当前生效 0否 1是';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `endpoint` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '端点';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `access_key_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'AccessKeyId(阿里云)';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `access_key_secret` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'AccessKeySecret(阿里云)';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `region` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '地域';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `bucket_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'Bucket名称';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `domain` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '访问域名';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `status` tinyint NULL DEFAULT '0' COMMENT '状态 0正常 1禁用';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `aox`.`sys_oss_config` MODIFY COLUMN `deleted` tinyint NULL DEFAULT '0' COMMENT '删除标记 0正常 1删除';
ALTER TABLE `aox`.`sys_banner` COMMENT='Banner轮播图表';
ALTER TABLE `aox`.`sys_oss_config` COMMENT='云存储配置表';
